# Generated by Django 5.2.1 on 2025-05-20 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="JobListing",
            fields=[
                (
                    "id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("company_name", models.CharField(max_length=200)),
                ("job_title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                ("application_url", models.URLField(blank=True, null=True)),
                ("location", models.CharField(blank=True, max_length=200, null=True)),
                ("industry", models.CharField(max_length=100)),
                ("flexibility", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "salary_range",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("reason_for_match", models.TextField(blank=True, null=True)),
                ("source", models.CharField(blank=True, max_length=50, null=True)),
                ("status", models.CharField(blank=True, max_length=50, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
