# Generated by Django 5.0.14 on 2025-06-30 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matcher", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="session_key",
        ),
        migrations.AlterField(
            model_name="savedjob",
            name="status",
            field=models.CharField(
                choices=[
                    ("not_applied", "Not Applied"),
                    ("viewed", "Viewed"),
                    ("applied", "Applied"),
                    ("interviewing", "Interviewing"),
                    ("offer", "Offer"),
                    ("rejected", "Rejected"),
                ],
                default="not_applied",
                max_length=20,
            ),
        ),
    ]
