# Generated by Django 5.0.14 on 2025-07-05 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matcher", "0002_remove_userprofile_session_key_alter_savedjob_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="cv_analysis_cache",
            field=models.JSONField(
                blank=True, help_text="用户画像分析结果缓存", null=True
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="supabase_synced_at",
            field=models.DateTimeField(
                blank=True, help_text="最后同步到Supabase的时间", null=True
            ),
        ),
    ]
