# Generated by Django 5.0.14 on 2025-07-05 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matcher", "0003_userprofile_cv_analysis_cache_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="savedjob",
            name="status",
            field=models.CharField(
                choices=[
                    ("not_applied", "Not Applied"),
                    ("bookmarked", "Bookmarked"),
                    ("applied", "Applied"),
                    ("interviewing", "Interviewing"),
                    ("offer", "Offer"),
                    ("rejected", "Rejected"),
                ],
                default="not_applied",
                max_length=20,
            ),
        ),
    ]
