# Generated by Django 5.2.1 on 2025-05-23 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matcher", "0004_coverletter"),
    ]

    operations = [
        migrations.AddField(
            model_name="matchedjob",
            name="match_details",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="savedjob",
            name="status",
            field=models.CharField(
                choices=[
                    ("not_applied", "Not Applied"),
                    ("applied", "Applied"),
                    ("interviewing", "Interviewing"),
                    ("offer_received", "Offer Received"),
                    ("rejected", "Rejected"),
                    ("accepted", "Accepted"),
                ],
                default="not_applied",
                max_length=20,
            ),
        ),
    ]
