# Generated by Django 5.2.1 on 2025-05-23 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matcher", "0005_matchedjob_match_details_alter_savedjob_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="matchedjob",
            name="match_details",
        ),
        migrations.AddField(
            model_name="joblisting",
            name="level",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
