# Generated by Django 5.2.1 on 2025-05-23 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matcher", "0006_remove_matchedjob_match_details_joblisting_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="matchsession",
            name="structured_user_profile_json",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="matchsession",
            name="user_preferences_text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
