# Generated by Django 5.2.1 on 2025-05-23 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matcher", "0007_matchsession_structured_user_profile_json_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="matchedjob",
            name="insights",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="matchedjob",
            name="tips",
            field=models.TextField(blank=True, null=True),
        ),
    ]
