# Generated by Django 4.2.21 on 2025-06-11 15:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("matcher", "0008_matchedjob_insights_matchedjob_tips"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkExperience",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_session_key", models.CharField(db_index=True, max_length=40)),
                (
                    "original_input",
                    models.TextField(
                        help_text="A short, memorable name for this work experience."
                    ),
                ),
                (
                    "structured_story",
                    models.TextField(
                        help_text="Describe the experience using the STAR method (Situation, Task, Action, Result).",
                        verbose_name="STAR Story",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
    ]
