# Generated by Django 4.2.21 on 2025-06-11 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("matcher", "0009_workexperience"),
    ]

    operations = [
        migrations.DeleteModel(
            name="WorkExperience",
        ),
    ]
