# Generated by Django 5.0.14 on 2025-06-11 19:56

import matcher.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matcher", "0010_delete_workexperience"),
    ]

    operations = [
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "session_key",
                    models.CharField(
                        editable=False, max_length=40, primary_key=True, serialize=False
                    ),
                ),
                ("user_cv_text", models.TextField(blank=True, null=True)),
                (
                    "cv_file",
                    models.FileField(
                        blank=True, null=True, upload_to=matcher.models.user_cv_path
                    ),
                ),
                ("user_preferences_text", models.TextField(blank=True, null=True)),
                (
                    "user_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
