# Generated by Django 5.0.14 on 2025-06-13 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matcher", "0011_experience_userprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomResume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_session_key", models.CharField(db_index=True, max_length=40)),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "job_listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_resumes",
                        to="matcher.joblisting",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
                "unique_together": {("user_session_key", "job_listing")},
            },
        ),
    ]
