# Generated by Django 5.0.14 on 2025-06-21 13:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("matcher", "0012_customresume"),
    ]

    operations = [
        migrations.AddField(
            model_name="joblisting",
            name="translated_description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
